### ISSUE TITLE
 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by ZamSul** [wangguanan/Pytorch-Person-REID-Baseline-Bag-of-Tricks#9]
Hi, I am trying to train the model but the following error is appearing.
```
/usr/local/lib/python3.6/dist-packages/sklearn/externals/joblib/externals/cloudpickle/cloudpickle.py:47: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
Traceback (most recent call last):
  File "main.py", line 134, in <module>
    main(config)
  File "main.py", line 14, in main
    loaders = Loaders(config)
  File "/home/zamra/PYreps/Person_ReId/Pytorch-Person-REID-Baseline-Bag-of-Tricks/core/data_loader/__init__.py", line 52, in __init__
    self._load()
  File "/home/zamra/PYreps/Person_ReId/Pytorch-Person-REID-Baseline-Bag-of-Tricks/core/data_loader/__init__.py", line 68, in _load
    self.duke_query_samples, self.duke_gallery_samples = self._get_test_samples('duke_test')
  File "/home/zamra/PYreps/Person_ReId/Pytorch-Person-REID-Baseline-Bag-of-Tricks/core/data_loader/__init__.py", line 93, in _get_test_samples
    query_samples = Samples4Duke(query_data_path, reorder=False)
  File "/home/zamra/PYreps/Person_ReId/Pytorch-Person-REID-Baseline-Bag-of-Tricks/core/data_loader/dataset.py", line 23, in __init__
    samples = self._load_images_path(self.samples_path)
  File "/home/zamra/PYreps/Person_ReId/Pytorch-Person-REID-Baseline-Bag-of-Tricks/core/data_loader/dataset.py", line 54, in _load_images_path
    root_path, _, files_name = os_walk(folder_dir)
TypeError: 'NoneType' object is not iterable

```

**Comment by wangguanan** [comment]
Hi, it seems that the direction is wrong.
can you replace the 'market_path' and 'duke_path' with your own path?
'''
# train
python main.py --market_path market_path --duke_path duke_path --output_path output_path/ --mode train 
'''
